Locations = {};

Locations.locations = {

    "-10|-10": { biome: "forest", hasPath: true, accessible: true },
    "-9|-10": { biome: "forest", hasPath: true, accessible: true },
    "-8|-10": { biome: "forest", hasPath: true, accessible: true },
    "-7|-10": { biome: "forest", hasPath: true, accessible: true },
    "-6|-10": { biome: "forest", hasPath: true, accessible: true },
    "-5|-10": { biome: "forest", hasPath: true, accessible: true },
    "-4|-10": { biome: "forest", hasPath: true, accessible: true },
    "-3|-10": { biome: "forest", hasPath: true, accessible: true },
    "-2|-10": { biome: "forest", hasPath: true, accessible: true },
    "-1|-10": { biome: "forest", hasPath: true, accessible: true },
    "0|-10": { biome: "forest", hasPath: true, accessible: true },
    "1|-10": { biome: "forest", hasPath: true, accessible: true },
    "2|-10": { biome: "forest", hasPath: true, accessible: true },
    "3|-10": { biome: "forest", hasPath: true, accessible: true },
    "4|-10": { biome: "forest", hasPath: true, accessible: true },
    "5|-10": { biome: "forest", hasPath: true, accessible: true },
    "6|-10": { biome: "forest", hasPath: true, accessible: true },
    "7|-10": { biome: "forest", hasPath: true, accessible: true },
    "8|-10": { biome: "forest", hasPath: true, accessible: true },
    "9|-10": { biome: "forest", hasPath: true, accessible: true },
    "10|-10": { biome: "forest", hasPath: true, accessible: true },


    "-10|-9": { biome: "forest", hasPath: true, accessible: true },
    "-9|-9": { biome: "forest", hasPath: true, accessible: true },
    "-8|-9": { biome: "forest", hasPath: true, accessible: true },
    "-7|-9": { biome: "forest", hasPath: true, accessible: true },
    "-6|-9": { biome: "forest", hasPath: true, accessible: true },
    "-5|-9": { biome: "forest", hasPath: true, accessible: true },
    "-4|-9": { biome: "forest", hasPath: true, accessible: true },
    "-3|-9": { biome: "forest", hasPath: true, accessible: true },
    "-2|-9": { biome: "forest", hasPath: true, accessible: true },
    "-1|-9": { biome: "forest", hasPath: true, accessible: true },
    "0|-9": { biome: "forest", hasPath: true, accessible: true },
    "1|-9": { biome: "forest", hasPath: true, accessible: true },
    "2|-9": { biome: "forest", hasPath: true, accessible: true },
    "3|-9": { biome: "forest", hasPath: true, accessible: true },
    "4|-9": { biome: "forest", hasPath: true, accessible: true },
    "5|-9": { biome: "forest", hasPath: true, accessible: true },
    "6|-9": { biome: "forest", hasPath: true, accessible: true },
    "7|-9": { biome: "forest", hasPath: true, accessible: true },
    "8|-9": { biome: "forest", hasPath: true, accessible: true },
    "9|-9": { biome: "forest", hasPath: true, accessible: true },
    "10|-9": { biome: "forest", hasPath: true, accessible: true },


    "-10|-8": { biome: "forest", hasPath: true, accessible: true },
    "-9|-8": { biome: "forest", hasPath: true, accessible: true },
    "-8|-8": { biome: "forest", hasPath: true, accessible: true },
    "-7|-8": { biome: "forest", hasPath: true, accessible: true },
    "-6|-8": { biome: "forest", hasPath: true, accessible: true },
    "-5|-8": { biome: "forest", hasPath: true, accessible: true },
    "-4|-8": { biome: "forest", hasPath: true, accessible: true },
    "-3|-8": { biome: "forest", hasPath: true, accessible: true },
    "-2|-8": { biome: "forest", hasPath: true, accessible: true },
    "-1|-8": { biome: "forest", hasPath: true, accessible: true },
    "0|-8": { biome: "forest", hasPath: true, accessible: true },
    "1|-8": { biome: "forest", hasPath: true, accessible: true },
    "2|-8": { biome: "forest", hasPath: true, accessible: true },
    "3|-8": { biome: "forest", hasPath: true, accessible: true },
    "4|-8": { biome: "forest", hasPath: true, accessible: true },
    "5|-8": { biome: "forest", hasPath: true, accessible: true },
    "6|-8": { biome: "forest", hasPath: true, accessible: true },
    "7|-8": { biome: "forest", hasPath: true, accessible: true },
    "8|-8": { biome: "forest", hasPath: true, accessible: true },
    "9|-8": { biome: "forest", hasPath: true, accessible: true },
    "10|-8": { biome: "forest", hasPath: true, accessible: true },


    "-10|-7": { biome: "forest", hasPath: true, accessible: true },
    "-9|-7": { biome: "forest", hasPath: true, accessible: true },
    "-8|-7": { biome: "forest", hasPath: true, accessible: true },
    "-7|-7": { biome: "forest", hasPath: true, accessible: true },
    "-6|-7": { biome: "forest", hasPath: true, accessible: true },
    "-5|-7": { biome: "forest", hasPath: true, accessible: true },
    "-4|-7": { biome: "forest", hasPath: true, accessible: true },
    "-3|-7": { biome: "forest", hasPath: true, accessible: true },
    "-2|-7": { biome: "forest", hasPath: true, accessible: true },
    "-1|-7": { biome: "forest", hasPath: true, accessible: true },
    "0|-7": { biome: "forest", hasPath: true, accessible: true },
    "1|-7": { biome: "forest", hasPath: true, accessible: true },
    "2|-7": { biome: "forest", hasPath: true, accessible: true },
    "3|-7": { biome: "forest", hasPath: true, accessible: true },
    "4|-7": { biome: "forest", hasPath: true, accessible: true },
    "5|-7": { biome: "forest", hasPath: true, accessible: true },
    "6|-7": { biome: "forest", hasPath: true, accessible: true },
    "7|-7": { biome: "forest", hasPath: true, accessible: true },
    "8|-7": { biome: "forest", hasPath: true, accessible: true },
    "9|-7": { biome: "forest", hasPath: true, accessible: true },
    "10|-7": { biome: "forest", hasPath: true, accessible: true },


    "-10|-6": { biome: "forest", hasPath: true, accessible: true },
    "-9|-6": { biome: "forest", hasPath: true, accessible: true },
    "-8|-6": { biome: "forest", hasPath: true, accessible: true },
    "-7|-6": { biome: "forest", hasPath: true, accessible: true },
    "-6|-6": { biome: "forest", hasPath: true, accessible: true },
    "-5|-6": { biome: "forest", hasPath: true, accessible: true },
    "-4|-6": { biome: "forest", hasPath: true, accessible: true },
    "-3|-6": { biome: "forest", hasPath: true, accessible: true },
    "-2|-6": { biome: "forest", hasPath: true, accessible: true },
    "-1|-6": { biome: "forest", hasPath: true, accessible: true },
    "0|-6": { biome: "forest", hasPath: true, accessible: true },
    "1|-6": { biome: "forest", hasPath: true, accessible: true },
    "2|-6": { biome: "forest", hasPath: true, accessible: true },
    "3|-6": { biome: "forest", hasPath: true, accessible: true },
    "4|-6": { biome: "forest", hasPath: true, accessible: true },
    "5|-6": { biome: "forest", hasPath: true, accessible: true },
    "6|-6": { biome: "forest", hasPath: true, accessible: true },
    "7|-6": { biome: "forest", hasPath: true, accessible: true },
    "8|-6": { biome: "forest", hasPath: true, accessible: true },
    "9|-6": { biome: "forest", hasPath: true, accessible: true },
    "10|-6": { biome: "forest", hasPath: true, accessible: true },


    "-10|-5": { biome: "forest", hasPath: true, accessible: true },
    "-9|-5": { biome: "forest", hasPath: true, accessible: true },
    "-8|-5": { biome: "forest", hasPath: true, accessible: true },
    "-7|-5": { biome: "forest", hasPath: true, accessible: true },
    "-6|-5": { biome: "forest", hasPath: true, accessible: true },
    "-5|-5": { biome: "forest", hasPath: true, accessible: true },
    "-4|-5": { biome: "forest", hasPath: true, accessible: true },
    "-3|-5": { biome: "forest", hasPath: true, accessible: true },
    "-2|-5": { biome: "forest", hasPath: true, accessible: true },
    "-1|-5": { biome: "forest", hasPath: true, accessible: true },
    "0|-5": { biome: "forest", hasPath: true, accessible: true },
    "1|-5": { biome: "forest", hasPath: true, accessible: true },
    "2|-5": { biome: "forest", hasPath: true, accessible: true },
    "3|-5": { biome: "forest", hasPath: true, accessible: true },
    "4|-5": { biome: "forest", hasPath: true, accessible: true },
    "5|-5": { biome: "forest", hasPath: true, accessible: true },
    "6|-5": { biome: "forest", hasPath: true, accessible: true },
    "7|-5": { biome: "forest", hasPath: true, accessible: true },
    "8|-5": { biome: "forest", hasPath: true, accessible: true },
    "9|-5": { biome: "forest", hasPath: true, accessible: true },
    "10|-5": { biome: "forest", hasPath: true, accessible: true },


    "-10|-4": { biome: "forest", hasPath: true, accessible: true },
    "-9|-4": { biome: "forest", hasPath: true, accessible: true },
    "-8|-4": { biome: "forest", hasPath: true, accessible: true },
    "-7|-4": { biome: "forest", hasPath: true, accessible: true },
    "-6|-4": { biome: "forest", hasPath: true, accessible: true },
    "-5|-4": { biome: "forest", hasPath: true, accessible: true },
    "-4|-4": { biome: "forest", hasPath: true, accessible: true },
    "-3|-4": { biome: "forest", hasPath: true, accessible: true },
    "-2|-4": { biome: "forest", hasPath: true, accessible: true },
    "-1|-4": { biome: "forest", hasPath: true, accessible: true },
    "0|-4": { biome: "forest", hasPath: true, accessible: true },
    "1|-4": { biome: "forest", hasPath: true, accessible: true },
    "2|-4": { biome: "forest", hasPath: true, accessible: true },
    "3|-4": { biome: "forest", hasPath: true, accessible: true },
    "4|-4": { biome: "forest", hasPath: true, accessible: true },
    "5|-4": { biome: "forest", hasPath: true, accessible: true },
    "6|-4": { biome: "forest", hasPath: true, accessible: true },
    "7|-4": { biome: "forest", hasPath: true, accessible: true },
    "8|-4": { biome: "forest", hasPath: true, accessible: true },
    "9|-4": { biome: "forest", hasPath: true, accessible: true },
    "10|-4": { biome: "forest", hasPath: true, accessible: true },


    "-10|-3": { biome: "forest", hasPath: true, accessible: true },
    "-9|-3": { biome: "forest", hasPath: true, accessible: true },
    "-8|-3": { biome: "forest", hasPath: true, accessible: true },
    "-7|-3": { biome: "forest", hasPath: true, accessible: true },
    "-6|-3": { biome: "forest", hasPath: true, accessible: true },
    "-5|-3": { biome: "forest", hasPath: true, accessible: true },
    "-4|-3": { biome: "forest", hasPath: true, accessible: true },
    "-3|-3": { biome: "forest", hasPath: true, accessible: true },
    "-2|-3": { biome: "forest", hasPath: true, accessible: true },
    "-1|-3": { biome: "forest", hasPath: true, accessible: true },
    "0|-3": { biome: "forest", hasPath: true, accessible: true },
    "1|-3": { biome: "forest", hasPath: true, accessible: true },
    "2|-3": { biome: "forest", hasPath: true, accessible: true },
    "3|-3": { biome: "forest", hasPath: true, accessible: true },
    "4|-3": { biome: "forest", hasPath: true, accessible: true },
    "5|-3": { biome: "forest", hasPath: true, accessible: true },
    "6|-3": { biome: "forest", hasPath: true, accessible: true },
    "7|-3": { biome: "forest", hasPath: true, accessible: true },
    "8|-3": { biome: "forest", hasPath: true, accessible: true },
    "9|-3": { biome: "forest", hasPath: true, accessible: true },
    "10|-3": { biome: "forest", hasPath: true, accessible: true },


    "-10|-2": { biome: "forest", hasPath: true, accessible: true },
    "-9|-2": { biome: "forest", hasPath: true, accessible: true },
    "-8|-2": { biome: "forest", hasPath: true, accessible: true },
    "-7|-2": { biome: "forest", hasPath: true, accessible: true },
    "-6|-2": { biome: "forest", hasPath: true, accessible: true },
    "-5|-2": { biome: "forest", hasPath: true, accessible: true },
    "-4|-2": { biome: "forest", hasPath: true, accessible: true },
    "-3|-2": { biome: "forest", hasPath: true, accessible: true },
    "-2|-2": { biome: "forest", hasPath: true, accessible: true },
    "-1|-2": { biome: "forest", hasPath: true, accessible: true },
    "0|-2": { biome: "forest", hasPath: true, accessible: true },
    "1|-2": { biome: "forest", hasPath: true, accessible: true },
    "2|-2": { biome: "forest", hasPath: true, accessible: true },
    "3|-2": { biome: "forest", hasPath: true, accessible: true },
    "4|-2": { biome: "forest", hasPath: true, accessible: true },
    "5|-2": { biome: "forest", hasPath: true, accessible: true },
    "6|-2": { biome: "forest", hasPath: true, accessible: true },
    "7|-2": { biome: "forest", hasPath: true, accessible: true },
    "8|-2": { biome: "forest", hasPath: true, accessible: true },
    "9|-2": { biome: "forest", hasPath: true, accessible: true },
    "10|-2": { biome: "forest", hasPath: true, accessible: true },


    "-10|-1": { biome: "forest", hasPath: true, accessible: true },
    "-9|-1": { biome: "forest", hasPath: true, accessible: true },
    "-8|-1": { biome: "forest", hasPath: true, accessible: true },
    "-7|-1": { biome: "forest", hasPath: true, accessible: true },
    "-6|-1": { biome: "forest", hasPath: true, accessible: true },
    "-5|-1": { biome: "forest", hasPath: true, accessible: true },
    "-4|-1": { biome: "forest", hasPath: true, accessible: true },
    "-3|-1": { biome: "forest", hasPath: true, accessible: true },
    "-2|-1": { biome: "forest", hasPath: true, accessible: true },
    "-1|-1": { biome: "forest", hasPath: true, accessible: true },
    "0|-1": { biome: "forest", hasPath: true, accessible: true },
    "1|-1": { biome: "forest", hasPath: true, accessible: true },
    "2|-1": { biome: "forest", hasPath: true, accessible: true },
    "3|-1": { biome: "forest", hasPath: true, accessible: true },
    "4|-1": { biome: "forest", hasPath: true, accessible: true },
    "5|-1": { biome: "forest", hasPath: true, accessible: true },
    "6|-1": { biome: "forest", hasPath: true, accessible: true },
    "7|-1": { biome: "forest", hasPath: true, accessible: true },
    "8|-1": { biome: "forest", hasPath: true, accessible: true },
    "9|-1": { biome: "forest", hasPath: true, accessible: true },
    "10|-1": { biome: "forest", hasPath: true, accessible: true },


    "-10|0": { biome: "forest", hasPath: true, accessible: true },
    "-9|0": { biome: "forest", hasPath: true, accessible: true },
    "-8|0": { biome: "forest", hasPath: true, accessible: true },
    "-7|0": { biome: "forest", hasPath: true, accessible: true },
    "-6|0": { biome: "forest", hasPath: true, accessible: true },
    "-5|0": { biome: "forest", hasPath: true, accessible: true },
    "-4|0": { biome: "forest", hasPath: true, accessible: true },
    "-3|0": { biome: "forest", hasPath: true, accessible: true },
    "-2|0": { biome: "forest", hasPath: true, accessible: true },
    "-1|0": { biome: "forest", hasPath: true, accessible: true },
    "0|0": { biome: "forest", hasPath: true, accessible: true },
    "1|0": { biome: "forest", hasPath: true, accessible: true },
    "2|0": { biome: "forest", hasPath: true, accessible: true },
    "3|0": { biome: "forest", hasPath: true, accessible: true },
    "4|0": { biome: "forest", hasPath: true, accessible: true },
    "5|0": { biome: "forest", hasPath: true, accessible: true },
    "6|0": { biome: "forest", hasPath: true, accessible: true },
    "7|0": { biome: "forest", hasPath: true, accessible: true },
    "8|0": { biome: "forest", hasPath: true, accessible: true },
    "9|0": { biome: "forest", hasPath: true, accessible: true },
    "10|0": { biome: "forest", hasPath: true, accessible: true },

    "-10|1": { biome: "forest", hasPath: true, accessible: true },
    "-9|1": { biome: "forest", hasPath: true, accessible: true },
    "-8|1": { biome: "forest", hasPath: true, accessible: true },
    "-7|1": { biome: "forest", hasPath: true, accessible: true },
    "-6|1": { biome: "forest", hasPath: true, accessible: true },
    "-5|1": { biome: "forest", hasPath: true, accessible: true },
    "-4|1": { biome: "forest", hasPath: true, accessible: true },
    "-3|1": { biome: "forest", hasPath: true, accessible: true },
    "-2|1": { biome: "forest", hasPath: true, accessible: true },
    "-1|1": { biome: "forest", hasPath: true, accessible: true },
    "0|1": { biome: "forest", hasPath: true, accessible: true },
    "1|1": { biome: "forest", hasPath: true, accessible: true },
    "2|1": { biome: "forest", hasPath: true, accessible: true },
    "3|1": { biome: "forest", hasPath: true, accessible: true },
    "4|1": { biome: "forest", hasPath: true, accessible: true },
    "5|1": { biome: "forest", hasPath: true, accessible: true },
    "6|1": { biome: "forest", hasPath: true, accessible: true },
    "7|1": { biome: "forest", hasPath: true, accessible: true },
    "8|1": { biome: "forest", hasPath: true, accessible: true },
    "9|1": { biome: "forest", hasPath: true, accessible: true },
    "10|1": { biome: "forest", hasPath: true, accessible: true },

    "-10|2": { biome: "forest", hasPath: true, accessible: true },
    "-9|2": { biome: "forest", hasPath: true, accessible: true },
    "-8|2": { biome: "forest", hasPath: true, accessible: true },
    "-7|2": { biome: "forest", hasPath: true, accessible: true },
    "-6|2": { biome: "forest", hasPath: true, accessible: true },
    "-5|2": { biome: "forest", hasPath: true, accessible: true },
    "-4|2": { biome: "forest", hasPath: true, accessible: true },
    "-3|2": { biome: "forest", hasPath: true, accessible: true },
    "-2|2": { biome: "forest", hasPath: true, accessible: true },
    "-1|2": { biome: "forest", hasPath: true, accessible: true },
    "0|2": { biome: "forest", hasPath: true, accessible: true },
    "1|2": { biome: "forest", hasPath: true, accessible: true },
    "2|2": { biome: "forest", hasPath: true, accessible: true },
    "3|2": { biome: "forest", hasPath: true, accessible: true },
    "4|2": { biome: "forest", hasPath: true, accessible: true },
    "5|2": { biome: "forest", hasPath: true, accessible: true },
    "6|2": { biome: "forest", hasPath: true, accessible: true },
    "7|2": { biome: "forest", hasPath: true, accessible: true },
    "8|2": { biome: "forest", hasPath: true, accessible: true },
    "9|2": { biome: "forest", hasPath: true, accessible: true },
    "10|2": { biome: "forest", hasPath: true, accessible: true },

    "-10|3": { biome: "forest", hasPath: true, accessible: true },
    "-9|3": { biome: "forest", hasPath: true, accessible: true },
    "-8|3": { biome: "forest", hasPath: true, accessible: true },
    "-7|3": { biome: "forest", hasPath: true, accessible: true },
    "-6|3": { biome: "forest", hasPath: true, accessible: true },
    "-5|3": { biome: "forest", hasPath: true, accessible: true },
    "-4|3": { biome: "forest", hasPath: true, accessible: true },
    "-3|3": { biome: "forest", hasPath: true, accessible: true },
    "-2|3": { biome: "forest", hasPath: true, accessible: true },
    "-1|3": { biome: "forest", hasPath: true, accessible: true },
    "0|3": { biome: "forest", hasPath: true, accessible: true },
    "1|3": { biome: "forest", hasPath: true, accessible: true },
    "2|3": { biome: "forest", hasPath: true, accessible: true },
    "3|3": { biome: "forest", hasPath: true, accessible: true },
    "4|3": { biome: "forest", hasPath: true, accessible: true },
    "5|3": { biome: "forest", hasPath: true, accessible: true },
    "6|3": { biome: "forest", hasPath: true, accessible: true },
    "7|3": { biome: "forest", hasPath: true, accessible: true },
    "8|3": { biome: "forest", hasPath: true, accessible: true },
    "9|3": { biome: "forest", hasPath: true, accessible: true },
    "10|3": { biome: "forest", hasPath: true, accessible: true },

    "-10|4": { biome: "forest", hasPath: true, accessible: true },
    "-9|4": { biome: "forest", hasPath: true, accessible: true },
    "-8|4": { biome: "forest", hasPath: true, accessible: true },
    "-7|4": { biome: "forest", hasPath: true, accessible: true },
    "-6|4": { biome: "forest", hasPath: true, accessible: true },
    "-5|4": { biome: "forest", hasPath: true, accessible: true },
    "-4|4": { biome: "forest", hasPath: true, accessible: true },
    "-3|4": { biome: "forest", hasPath: true, accessible: true },
    "-2|4": { biome: "forest", hasPath: true, accessible: true },
    "-1|4": { biome: "forest", hasPath: true, accessible: true },
    "0|4": { biome: "forest", hasPath: true, accessible: true },
    "1|4": { biome: "forest", hasPath: true, accessible: true },
    "2|4": { biome: "forest", hasPath: true, accessible: true },
    "3|4": { biome: "forest", hasPath: true, accessible: true },
    "4|4": { biome: "forest", hasPath: true, accessible: true },
    "5|4": { biome: "forest", hasPath: true, accessible: true },
    "6|4": { biome: "forest", hasPath: true, accessible: true },
    "7|4": { biome: "forest", hasPath: true, accessible: true },
    "8|4": { biome: "forest", hasPath: true, accessible: true },
    "9|4": { biome: "forest", hasPath: true, accessible: true },
    "10|4": { biome: "forest", hasPath: true, accessible: true },

    "-10|5": { biome: "forest", hasPath: true, accessible: true },
    "-9|5": { biome: "forest", hasPath: true, accessible: true },
    "-8|5": { biome: "forest", hasPath: true, accessible: true },
    "-7|5": { biome: "forest", hasPath: true, accessible: true },
    "-6|5": { biome: "forest", hasPath: true, accessible: true },
    "-5|5": { biome: "forest", hasPath: true, accessible: true },
    "-4|5": { biome: "forest", hasPath: true, accessible: true },
    "-3|5": { biome: "forest", hasPath: true, accessible: true },
    "-2|5": { biome: "forest", hasPath: true, accessible: true },
    "-1|5": { biome: "forest", hasPath: true, accessible: true },
    "0|5": { biome: "forest", hasPath: true, accessible: true },
    "1|5": { biome: "forest", hasPath: true, accessible: true },
    "2|5": { biome: "forest", hasPath: true, accessible: true },
    "3|5": { biome: "forest", hasPath: true, accessible: true },
    "4|5": { biome: "forest", hasPath: true, accessible: true },
    "5|5": { biome: "forest", hasPath: true, accessible: true },
    "6|5": { biome: "forest", hasPath: true, accessible: true },
    "7|5": { biome: "forest", hasPath: true, accessible: true },
    "8|5": { biome: "forest", hasPath: true, accessible: true },
    "9|5": { biome: "forest", hasPath: true, accessible: true },
    "10|5": { biome: "forest", hasPath: true, accessible: true },

    "-10|6": { biome: "forest", hasPath: true, accessible: true },
    "-9|6": { biome: "forest", hasPath: true, accessible: true },
    "-8|6": { biome: "forest", hasPath: true, accessible: true },
    "-7|6": { biome: "forest", hasPath: true, accessible: true },
    "-6|6": { biome: "forest", hasPath: true, accessible: true },
    "-5|6": { biome: "forest", hasPath: true, accessible: true },
    "-4|6": { biome: "forest", hasPath: true, accessible: true },
    "-3|6": { biome: "forest", hasPath: true, accessible: true },
    "-2|6": { biome: "forest", hasPath: true, accessible: true },
    "-1|6": { biome: "forest", hasPath: true, accessible: true },
    "0|6": { biome: "forest", hasPath: true, accessible: true },
    "1|6": { biome: "forest", hasPath: true, accessible: true },
    "2|6": { biome: "forest", hasPath: true, accessible: true },
    "3|6": { biome: "forest", hasPath: true, accessible: true },
    "4|6": { biome: "forest", hasPath: true, accessible: true },
    "5|6": { biome: "forest", hasPath: true, accessible: true },
    "6|6": { biome: "lake", hasPath: false, accessible: false },
    "7|6": { biome: "lake", hasPath: false, accessible: false },
    "8|6": { biome: "lake", hasPath: false, accessible: false },
    "9|6": { biome: "forest", hasPath: true, accessible: true },
    "10|6": { biome: "forest", hasPath: true, accessible: true },

    "-10|7": { biome: "forest", hasPath: true, accessible: true },
    "-9|7": { biome: "forest", hasPath: true, accessible: true },
    "-8|7": { biome: "forest", hasPath: true, accessible: true },
    "-7|7": { biome: "forest", hasPath: true, accessible: true },
    "-6|7": { biome: "forest", hasPath: true, accessible: true },
    "-5|7": { biome: "forest", hasPath: true, accessible: true },
    "-4|7": { biome: "forest", hasPath: true, accessible: true },
    "-3|7": { biome: "forest", hasPath: true, accessible: true },
    "-2|7": { biome: "forest", hasPath: true, accessible: true },
    "-1|7": { biome: "forest", hasPath: true, accessible: true },
    "0|7": { biome: "forest", hasPath: true, accessible: true },
    "1|7": { biome: "forest", hasPath: true, accessible: true },
    "2|7": { biome: "forest", hasPath: true, accessible: true },
    "3|7": { biome: "forest", hasPath: true, accessible: true },
    "4|7": { biome: "lake", hasPath: false, accessible: false },
    "5|7": { biome: "lake", hasPath: false, accessible: false },
    "6|7": { biome: "lake", hasPath: false, accessible: false },
    "7|7": { biome: "lake", hasPath: false, accessible: false },
    "8|7": { biome: "lake", hasPath: false, accessible: false },
    "9|7": { biome: "forest", hasPath: true, accessible: true },
    "10|7": { biome: "forest", hasPath: true, accessible: true },

    "-10|8": { biome: "forest", hasPath: true, accessible: true },
    "-9|8": { biome: "forest", hasPath: true, accessible: true },
    "-8|8": { biome: "forest", hasPath: true, accessible: true },
    "-7|8": { biome: "forest", hasPath: true, accessible: true },
    "-6|8": { biome: "forest", hasPath: true, accessible: true },
    "-5|8": { biome: "forest", hasPath: true, accessible: true },
    "-4|8": { biome: "forest", hasPath: true, accessible: true },
    "-3|8": { biome: "forest", hasPath: true, accessible: true },
    "-2|8": { biome: "forest", hasPath: true, accessible: true },
    "-1|8": { biome: "forest", hasPath: true, accessible: true },
    "0|8": { biome: "forest", hasPath: true, accessible: true },
    "1|8": { biome: "forest", hasPath: true, accessible: true },
    "2|8": { biome: "forest", hasPath: true, accessible: true },
    "3|8": { biome: "forest", hasPath: true, accessible: true },
    "4|8": { biome: "forest", hasPath: true, accessible: true },
    "5|8": { biome: "lake", hasPath: false, accessible: false },
    "6|8": { biome: "lake", hasPath: false, accessible: false },
    "7|8": { biome: "lake", hasPath: false, accessible: false },
    "8|8": { biome: "lake", hasPath: false, accessible: false },
    "9|8": { biome: "forest", hasPath: true, accessible: true },
    "10|8": { biome: "forest", hasPath: true, accessible: true },

    "-10|9": { biome: "forest", hasPath: true, accessible: true },
    "-9|9": { biome: "forest", hasPath: true, accessible: true },
    "-8|9": { biome: "forest", hasPath: true, accessible: true },
    "-7|9": { biome: "forest", hasPath: true, accessible: true },
    "-6|9": { biome: "forest", hasPath: true, accessible: true },
    "-5|9": { biome: "forest", hasPath: true, accessible: true },
    "-4|9": { biome: "forest", hasPath: true, accessible: true },
    "-3|9": { biome: "forest", hasPath: true, accessible: true },
    "-2|9": { biome: "forest", hasPath: true, accessible: true },
    "-1|9": { biome: "forest", hasPath: true, accessible: true },
    "0|9": { biome: "forest", hasPath: true, accessible: true },
    "1|9": { biome: "forest", hasPath: true, accessible: true },
    "2|9": { biome: "forest", hasPath: true, accessible: true },
    "3|9": { biome: "forest", hasPath: true, accessible: true },
    "4|9": { biome: "forest", hasPath: true, accessible: true },
    "5|9": { biome: "forest", hasPath: true, accessible: true },
    "6|9": { biome: "lake", hasPath: false, accessible: false },
    "7|9": { biome: "lake", hasPath: false, accessible: false },
    "8|9": { biome: "forest", hasPath: true, accessible: true },
    "9|9": { biome: "forest", hasPath: true, accessible: true },
    "10|9": { biome: "forest", hasPath: true, accessible: true },

    "-10|10": { biome: "forest", hasPath: true, accessible: true },
    "-9|10": { biome: "forest", hasPath: true, accessible: true },
    "-8|10": { biome: "forest", hasPath: true, accessible: true },
    "-7|10": { biome: "forest", hasPath: true, accessible: true },
    "-6|10": { biome: "forest", hasPath: true, accessible: true },
    "-5|10": { biome: "forest", hasPath: true, accessible: true },
    "-4|10": { biome: "forest", hasPath: true, accessible: true },
    "-3|10": { biome: "forest", hasPath: true, accessible: true },
    "-2|10": { biome: "forest", hasPath: true, accessible: true },
    "-1|10": { biome: "forest", hasPath: true, accessible: true },
    "0|10": { biome: "forest", hasPath: true, accessible: true },
    "1|10": { biome: "forest", hasPath: true, accessible: true },
    "2|10": { biome: "forest", hasPath: true, accessible: true },
    "3|10": { biome: "forest", hasPath: true, accessible: true },
    "4|10": { biome: "forest", hasPath: true, accessible: true },
    "5|10": { biome: "forest", hasPath: true, accessible: true },
    "6|10": { biome: "forest", hasPath: true, accessible: true },
    "7|10": { biome: "forest", hasPath: true, accessible: true },
    "8|10": { biome: "forest", hasPath: true, accessible: true },
    "9|10": { biome: "forest", hasPath: true, accessible: true },
    "10|10": { biome: "forest", hasPath: true, accessible: true },







};

var map = [], loc,
    ri = 0;
for (var r = -30; r <= 30; r++) {
    map.push([]);
    for (var c = -30; c <= 30; c++) {
        loc = Locations.locations[c+"|"+r];
        if (loc != undefined) {
            loc.loc = c + "|" + r;
        }

        map[ri].push(loc);
    };
    ri++;
};

Locations.asMap = map;

Locations.get = function (l) {
    return Locations.locations[l];
}
